### PR TITLE
Release 4.0.0.RC

### LINKED ISSUE #17: Deploy to Maven Central
### TODOs
 
- [x] Update metadata according to https://central.sonatype.org/pages/requirements.html
- [x] Set up GPG signing usign https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F
- [x] Make sure profile still allows GH Actions to work
- [x] Make sure snapshots are signed
- [x] Make sure snapshots are pushed to OSSRH
- [x] Write back after a success to https://bugs.eclipse.org/bugs/show_bug.cgi?id=569263 so that OSSRH flips the switch

### Links

https://bugs.eclipse.org/bugs/show_bug.cgi?id=569263 for tracking

https://wiki.eclipse.org/IT_Infrastructure_Doc#Publish_to_Maven_Central checklist

### PR DESCRIPTION
**Pull request by berezovskyi**
## Description

Final milestone release before 4.0.0

## Checklist

- [ ] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [ ] This PR was tested on at least one Lyo OSLC server or adds unit/integration tests.
- [x] This PR does NOT break the API

## Issues

Closes #17

### CODE REVIEW

**Comment by berezovskyi** [comment]
Not tested the RC itself but RefImpl and sample Lyo adaptors work with the latest SNAPSHOT

**Comment by berezovskyi** [comment]
Ah, I love the new Maven Enforcer plugin: https://github.com/eclipse/lyo/runs/1512313664?check_suite_focus=true#step:5:63

**Comment by berezovskyi** [comment]
sorry @jadelkhoury but we can't keep lyo.domains POM generated: https://github.com/eclipse/lyo/pull/55/commits/ff977ad62a34365c14be3234ac0a41dca6f92412

**Comment by berezovskyi** [comment]
I am also happy to report we can also build successfully on JDK 11 (current LTS) and JDK 15 (current stable):

image

Github CI and Jenkins both use JDK 8 for widest compatibility.

**Review by jamsden — APPROVED** [review]

**Pull request merged**
