### PR TITLE
Fix Dialog URL on ServiceProviderFactory

### LINKED ISSUE #235: Dialog URL uses the API URL
When generating a `ServiceProvider` using the `ServiceProviderFactory` class and the URL of the context is sent to the `createServiceProvider` method for being used for the selection and creation dialog URL it does not work,   the dialog URL are the same as the API.

### PR DESCRIPTION
**Pull request by isccarrasco**
## Description

Solves the issue found in the ServiceProviderFactory in which the URL for the Dialogs are assigned to the same URL of the OSL API, the fix is to set the URL to the web application in which the html files are hosted

## Checklist

- [ ] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [x] This PR was tested on at least one Lyo OSLC server or adds unit/integration tests.
- [x] This PR does NOT break the API

## Issues

Closes #235 

_(use exactly this syntax to link to issues, one issue per statement only!)_

### CODE REVIEW

**Comment by berezovskyi** [comment]
@isccarrasco thank you for the PR! Looks good to me but we need to test it because I forgot the difference between the two arguments and we should be able to merge it soon.

**Comment by berezovskyi** [comment]
Mario, I just took a look at how this code is used now. Sadly, we don't have any test coverage for this. Right now the adaptors during initialization provide the base URI via `baseUri` and set `genericBaseUri` to an empty string `""`. The `dialogUri` is a relative URI path fragment that is then concatenated with the base URI.

Instead, the `genericBaseUri` is used to auto-generate the URIs of the dialogs with the `dialogUri` property. I don't think there is any code known to me that relies on "generic" URIs because they still have to point to existing pages that serve dialogs (and in that case it would not hurt to give a proper dialog URI path fragment).

How do you hit this problem? Our code calls `ServiceProviderFactory.createServiceProvider` with a proper `baseUri`, empty `genericBaseUri`, and the Dialog annotation looks like this:

`@org.eclipse.lyo.oslc4j.core.annotation.OslcDialog(resourceTypes={"http://open-services.net/ns/rm#Requirement"}, usages={}, label="SelectionDialog1", hintWidth="0px", hintHeight="0px", title="SelectionDialog1", uri="requirements/selector")`

Screen Shot 2022-02-12 at 18 37 09

Screen Shot 2022-02-12 at 18 41 39

Screen Shot 2022-02-12 at 18 46 44

I am guessing you are passing the full URI to `dialogUri`? I can totally see how could this be confusing. I think the reason the implementation is done this way is because you cannot use non-const expressions in `@Dialog` annotations. Maybe we should change the parameter name to `relativeUri` instead of `uri` or add a check for URI being absolute and then ignore both the base URI and the "generic" base URI.

Also, how are you using those "generic" base URIs? I am thinking to deprecate URI guessing for dialogs that are not fully annotated altogether to avoid confusion.

CC @jadelkhoury

**Comment by jadelkhoury** [comment]
Hi

I just tried to walk through the code. I am not sure what this change can solve. Can you please Mario? I can see though how this can be problematic since the genericBaseUri seem to have a whole different purpose. Making the suggested change will certainly change the current behaviour.

as suggested by @berezovskyi , will not passing the baseURI as you expect it to be do the job?

**Comment by jadelkhoury** [comment]
So, I normally set the baseUri to OSLC4JUtils.getServletURI() to make it refer to the same base as hte rest of the OSLC server. But I cannot see any thing hindering passing any other parameter.

**Comment by berezovskyi** [comment]
add to whitelist

**Comment by berezovskyi** [comment]
I removed the 5.0 milestone not to block the release.

**Comment by berezovskyi** [comment]
Closing this PR without merging. @isccarrasco if you still have this problem, please reply to https://github.com/eclipse/lyo/pull/236#issuecomment-1037363194 and we will consider reopening it. Thank you!

**Pull request closed without merging**
