### PR TITLE
promcode domain

### PR DESCRIPTION
**Pull request by Jad-el-khoury**
## Description

Introducing the PROMCODE domain

## Checklist

- [ ] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [ ] This PR was tested on at least one Lyo OSLC server (e.g. manual workflow on [Lyo Sample](https://github.com/OSLC/lyo-samples/actions/workflows/maven-smoke-manual.yml) and [OSLC RefImpl](https://github.com/oslc-op/refimpl/actions/workflows/maven-acceptance-manual.yml)) or adds unit/integration tests.
- [X] This PR does NOT break the API

### CODE REVIEW

**Comment by Jad-el-khoury** [comment]
PROMCODE

**Comment by Jad-el-khoury** [comment]
The domain code builds. I want to first make sure a server can run before we commit.

**Comment by berezovskyi** [comment]
I didn't have time to compare the diagram in detail to the spec HTML but I saw your note about decimal being replaced by an integer. Decimal is a high precision float, higher than double. At the same time, properties mentioned by you like `prom:sequenceNumber` should not be denoted by a float, unless I misunderstand something.

**Comment by Jad-el-khoury** [comment]
> properties mentioned by you like `prom:sequenceNumber` should not be denoted by a float, unless I misunderstand something.

Not sure what you mean @berezovskyi . The spec states that they are decimal, They should not be float, nor integer. Currently LyoDesigner does not support decimal, but I wanted to put something, just to get started.

**Comment by ShigeakiMatsumoto** [comment]
Hi, I am an editor of PROMCODE specification.
At first, thank you for your impressive work of domain modeling.
 
The following points are different from our intent.  Could you consider our idea as follows?

 1.  Lyo Designer doesn't provide 'Decimal' type, so we would like to assign other types as follows: 
     - '_sequenceNumber_' attribute in each resources are regarded as  'Integer' type in Lyo Designer
     - Other attributes with 'Decimal' type are regarded as 'float' type in Lyo Designer
          a)  '_valueOfMeasure_' attribute in **Measure** resource 
          b)  '_actualSize_' attribute in **ScopeItem** resource 
          c)   '_plannedSize_' attribute in **ScopeItem** resource 
  
      For example,
         The  '_sequenceNumber_' is used to arrange resources in this order.
         Other attributes is used to show volume size of deliverables such as  '1.2KL steps of code'.
 
  2.  Attributes which is 'datetime' type would be better to regard as 'dateTime' type in Lyo Designer
         a) '_date_' attribute in **Measurement** resource
         b) '_date_' attribute in **Report** resource
         c) '_date_' attribute in **Plan** resource
         d) '_date_' attribute in **RiskCollection** resource
         e) '_date_' attribute in **ManagedItemCollection** abstract resource
         f) '_date_' attribute in in **IssueCollection** resource
         
  3. '_observe_' attrbute  should connect between '**Measure**' and '**Measurement**' resources

**Comment by hoy3** [comment]
Thank you for the work, it looks great and I have few comments as below.
- Arfitact, ScopeItem and WorkItem are sub-class of ManagedItem.
- Plan, Report, IssueCollection and RiskCollection are sub-class of ManagedItemCollection

**Comment by berezovskyi** [comment]
@ShigeakiMatsumoto what is the reason for using the Decimal type as a sequence number? You can't really use equality to check if two decimals are equal. Shouldn't it be a long? Or BigInteger (XSD integer)?

**Comment by mwakao** [comment]
I think sequenceNumber is decimal because we just want to know the order of resources. For the purpose, integer is enough in most case. So, @ShigeakiMatsumoto mentioned, sequence number can be an integer in Lyo Designer. 
The edge case might be
- User created resources with sequence number 1 and 2
- After that, the user wants to add another resource between them
- Then user may want to have the sequence number 1.5.

**Comment by berezovskyi** [comment]
Sorry, didn't mean to do that, hit the wrong button on the phone.

Thanks Jad!

**Comment by Jad-el-khoury** [comment]
I have now made the changes suggested by @ShigeakiMatsumoto & @hoy3! 
Can you please check! Are we good?

**Comment by hoy3** [comment]
Thank you for the update, Jad! Class hierarchy looks fine.

**Comment by mwakao** [comment]
@Jad-el-khoury we have reviewed the model. It looks good to us. Thank you.

**Comment by berezovskyi** [comment]
@hoy3 @mwakao the domain model classes should appear in Lyo 6.0.0 release. They should be available now if you use a snapshot version:

```xml
<dependency>
  <groupId>org.eclipse.lyo</groupId>
  <artifactId>oslc-domains</artifactId>
  <version>6.0.0-SNAPSHOT</version>
</dependency>
```

**Pull request merged**
