### PR TITLE
fix: avoid exception in mostConcreteResourceType()

### LINKED ISSUE #259: JenaModelHelper cannot detect most concrete class (raising an exception) even when such a class exists.
The method getMostConcreteClassOf() in org.eclipse.lyo.oslc4j.provider.jena.ordfm.ResourcePackages incorrectly triggers an exception when trying to select the most concrete class, if the classes are listed in a certain order.

One particular scenario (there may be others) that causes this error is when the candidate classes are listed in increasing specialisation.

The while-loop is being prematurely ended since the list size is being decreased within the loop, by removing items. Later candidates are not tested.

https://github.com/eclipse/lyo/blob/7a83a881facdf94bbed032d1f509b2085a39e6b3/core/oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/ordfm/ResourcePackages.java#L116

### PR DESCRIPTION
**Pull request by jadelkhoury**
## Description

The method getMostConcreteClassOf() in org.eclipse.lyo.oslc4j.provider.jena.ordfm.ResourcePackages incorrectly triggers an exception when trying to select the most concrete class, if the classes are listed in a certain order.

This test illustrates when it fails; namely when the candidate classes are listed in increasing specialisation.

See https://github.com/eclipse/lyo/issues/259 for details

## Checklist

- [ ] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [ ] This PR was tested on at least one Lyo OSLC server or adds unit/integration tests.
- [ ] This PR does NOT break the API

## Issues

Closes #259

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@berezovskyi What do you think of the proposed solution? I was not really involved when this new feature was introduced. Hope you have a better bigger picture of how it is supposed to work.

**Comment by berezovskyi** [comment]
@jadelkhoury I am not sure the proposed solution is working because the tests are still failing.

**Comment by berezovskyi** [comment]
I think I touched the file in question when I was applying IntelliJ's suggested migrations for using latest Java 8 features. I don't think the PR is relevant any more as the new code should ensure the right index is used when deleting the item.

But I would like to keep the test you introduced. Let me try to resolve a conflict (by discarding your change).

**Comment by berezovskyi** [comment]
@jadelkhoury looks like the new method does not allow to apply a check on every removal.

I restored your fix and also fixed the unit test. The fix was very simple: there was a unit test checking the annotation-based package scanning and it checked the number of detected classes. Since you added `WildDog`, there was one more detected class and the unit test tripped. I just increased the expected count.

Should be good to merge once tests pass and I add a CHANGELOG entry.

**Comment by berezovskyi** [comment]
@jadelkhoury the tests pass on all JDKs and I pushed the CHANGELOG entry. Ready to merge if it looks good to you.

**Pull request merged**
