### PR TITLE
Tests that demonstrate issue #111 (OslcCoreInvalidValueTypeException is incorrectly thrown when a resource property is annotated to be represented as "inlined")

### LINKED ISSUE #111: OslcCoreInvalidValueTypeException is incorrectly thrown when a resource property is annotated to be represented as "inlined"
The following annotation ought to be ok. One has a property that references to a java class, whose content ought to be be fully inlined when marshalled as RDF.

@OslcValueType(ValueType.Resource)
@OslcRepresentation(Representation.Inline)
public InlinedShape getInlines() {
}

This is to be compared to how local resources are to be handled. Only difference is that a local resource ought not have a URL defined.
@OslcValueType(ValueType.LocalResource)
public LocalShape getReferencesAsLocal() {
}

But the first annotations result in an OslcCoreInvalidValueTypeException being incorrectly thrown when a resource property is annotated to be represented as "inlined".

Note that although the validateUserSpecifiedRepresentation() (which is meant to check for invalid representations) does not throw an OslcCoreInvalidRepresentationException.
https://github.com/eclipse/lyo/blob/4a61c7707ab95f7e3fdac179dd43dba9753a4bd6/core/oslc4j-core/src/main/java/org/eclipse/lyo/oslc4j/core/model/ResourceShapeFactory.java#L452

It is the validateUserSpecifiedValueType() method that throws an OslcCoreInvalidValueTypeException 
https://github.com/eclipse/lyo/blob/4a61c7707ab95f7e3fdac179dd43dba9753a4bd6/core/oslc4j-core/src/main/java/org/eclipse/lyo/oslc4j/core/model/ResourceShapeFactory.java#L416

### PR DESCRIPTION
**Pull request by jadelkhoury**
## Description

Solves issue #111 (OslcCoreInvalidValueTypeException is incorrectly thrown when a resource property is annotated to be represented as "inlined")

## Checklist

- [x] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [x] This PR was tested on at least one Lyo OSLC server or adds unit/integration tests.
- [x] This PR does NOT break the API

## Issues

Closes #111; 

_(use exactly this syntax to link to issues, one issue per statement only!)_

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@jamsden ! I would be great to get your input about the most appropriate way to handle Inlined resources.
@berezovskyi! Need your feedback on the unit tests I made.

**Comment by jamsden** [comment]
In general inline should be treated as a use case optimization - the inlined content is expected to be needed with the enclosing resource in most use cases, and is included to avoid extra gets. In terms of representation in Java classes, inline shouldn't matter in the reference implementations, real resource URIs should be used if possible. This way inline doesn't result in special cases.

**Comment by jadelkhoury** [comment]
image

**Comment by jadelkhoury** [comment]
@berezovskyi See the instructions under https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/61 on how to test this!

**Comment by jadelkhoury** [comment]
> In general inline should be treated as a use case optimization - the inlined content is expected to be needed with the enclosing resource in most use cases, and is included to avoid extra gets. In terms of representation in Java classes, inline shouldn't matter in the reference implementations, real resource URIs should be used if possible. This way inline doesn't result in special cases.

@jim! It is indeed a special case where one needs to optimize the respond and embed information and avoid extra GETs.
This pull request is actually a bug fix, since Lyo does not allow support for inlining. An exception is raised as soon as one tries to annotate an attribute as inlined.

**Comment by berezovskyi** [comment]
Looking at my notes, we already reviewed this PR with @jadelkhoury over a call and the PR looks good to me. We can make a 4.1.0.alpha2 release with just this change added so that Lyo users (who have migrated to Lyo 4.0 successfully) can check if this breaks anything for them (it shouldn't).

**Comment by berezovskyi** [comment]
@jadelkhoury any ideas why there is build failure in your PR for the Validation library?

**Review by berezovskyi — APPROVED** [review]

**Comment by jadelkhoury** [comment]
> @jadelkhoury any ideas why there is build failure in your PR for the Validation library?

@berezovskyi No idea. but I am not sure about the status of this validation library. should we wait with the merge of this pull request hten?

**Comment by jadelkhoury** [comment]
@berezovskyi I fixed the problem with the SHACL library.
How do I update the Changelog? It might be worth adding an entry about this change.

**Pull request merged**
