### PR TITLE
Refactor modules to avoid dependency on Servlet or Wink where possible

### PR DESCRIPTION
**Pull request by berezovskyi**
## Description

Essentially the same thing as #282 but in a backwards-compatible way.

## Checklist

- [x] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [ ] This PR was tested on at least one Lyo OSLC server or adds unit/integration tests.
- [x] This PR does NOT break the API

### CODE REVIEW

**Comment by berezovskyi** [comment]
TODOs on me:

- [ ] rename `provider-common-jee` to `lyo-core-settings`
- [ ] move `lyo-core-settings` from server to core
- [ ] list changes in the README
- [ ] list planned changes in Lyo 6 or log as an issue

**Comment by jad-elkhoury** [comment]
> ## Merge state
> Add more commits by pushing to the `[core-noservlet](/eclipse/lyo/tree/core-noservlet)` branch on [eclipse/lyo](/eclipse/lyo).
> 
> Show all checks
> ### All checks have passed
> 8 successful checks
> Ready for review
> This pull request is still a work in progress
> Draft pull requests cannot be merged.
> Squash and merge
> You can also [open this in GitHub Desktop](https://desktop.github.com) or view command line instructions .
> 
> [@jad-elkhoury](/jad-elkhoury)

We also said we rename the lyo-core-model module.

**Comment by jad-elkhoury** [comment]
> TODOs on me:
> 
> * [ ]  rename `provider-common-jee` to `lyo-core-settings`
> * [ ]  move `lyo-core-settings` from server to core
> * [ ]  list changes in the README
> * [ ]  list planned changes in Lyo 6 or log as an issue

We also said we rename the lyo-core-model module.

**Comment by berezovskyi** [comment]
Use oslc4j in Lyo 5 and move en masse in Lyo 6.

**Comment by berezovskyi** [comment]
@jad-elkhoury ready for your review.

**Comment by berezovskyi** [comment]
All the breaking changes planned for 6.0 from this PR were logged and can be seen under https://github.com/eclipse/lyo/issues?q=is%3Aopen+is%3Aissue+label%3A%22Xtra%3A+Breaking%22+milestone%3A6.0

**Pull request merged**
